"""
================================================================================
File: cart_dao.py
Description: Data Access Object for shopping cart operations
Author: Rocket Software NextGen Academy
Date: 2026
================================================================================
This module provides database operations for shopping cart management including:
- Cart creation and retrieval
- Adding/removing items to/from cart
- Cart item quantity updates
- Full cart clearing for checkout
================================================================================
"""

import os
import configparser

# Load database configuration
config = configparser.ConfigParser()
config.read('Backend/DatabaseAccess/config.ini')
clidriver_path = config['database']['clidriver_path']

# Set up IBM Db2 CLI driver paths
os.add_dll_directory(f"{clidriver_path}/bin")
driver_path = f"{clidriver_path}/bin/amd64.VC12.CRT"
os.environ["PATH"] = driver_path + ";" + os.environ.get("PATH", "")

import ibm_db


class CartDAO:
    """
    Data Access Object for Cart table operations.
    
    Handles all database interactions related to shopping carts and cart items
    including cart lifecycle management and item manipulation.
    """
    
    def __init__(self, pool):
        """
        Initialize CartDAO with a database connection pool.
        
        Inputs:
            pool (IBMDBConnectionPool): Database connection pool instance
        
        Outputs:
            None
        """
        self.pool = pool
    
    def create_cart(self, user_id):
        """
        Create a new shopping cart for a user.
        
        Inputs:
            user_id (int): User's unique identifier
        
        Outputs:
            dict: {"status": "success"} on success
                  {"status": "error", "reason": str} on failure
        
        Side Effects:
            Inserts new cart record in CARTS table
            Commits transaction on success, rolls back on failure
        
        Notes:
            Cart ID is auto-generated by database
            Default cart status is 'active'
        """
        conn = self.pool.get_connection()
        try:
            sql = """
                    INSERT INTO USER01.CARTS (USER_ID)
                    VALUES (?)
            """
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, user_id)
            ibm_db.execute(stmt)
            ibm_db.commit(conn)
            return {"status": "success"}
        except Exception as e:
            ibm_db.rollback(conn)
            error_code = ibm_db.conn_error(conn)
            error_msg = ibm_db.conn_errormsg(conn)
            return {"status": "error", "reason": str(e)}
        finally:
            self.pool.return_connection(conn)

    def get_cart_id(self, user_id):
        """
        Retrieve cart ID for a user.
        
        Inputs:
            user_id (int): User's unique identifier
        
        Outputs:
            dict: {"status": "success", "output": list with cart ID}
                  {"status": "error", "reason": str} on failure
        
        Notes:
            Returns empty list if user has no cart
            Calling code should check for empty result and create cart if needed
        """
        conn = self.pool.get_connection()
        try:
            sql =  """
                    SELECT ID FROM USER01.CARTS WHERE USER_ID = ?
                    """
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, user_id)
            ibm_db.execute(stmt)
            results = []
            row = ibm_db.fetch_assoc(stmt)
            while row:
                results.append(row)
                row = ibm_db.fetch_assoc(stmt)
            return {"status": "success", "output": results}
        except Exception as e:
            return {"status": "error", "reason": str(e)}
        finally:
            self.pool.return_connection(conn)
   

    def get_cart(self, user_id):
        """
        Retrieve complete cart contents with full product details.
        
        Inputs:
            user_id (int): User's unique identifier
        
        Outputs:
            dict: {"status": "success", "output": list of cart items with details}
                  {"status": "error", "reason": str} on failure
        
        Notes:
            Returns detailed information including:
            - Cart item ID, quantity, price
            - Product SKU, name, series, style, modifier
            - Inventory details
            - Product images (if available)
            Uses 10-table JOIN for complete product information
            Only returns active cart items
        """
        conn = self.pool.get_connection()
        try:
            sql =  """
                        SELECT
                            CI.ID AS CART_ITEM_ID,
                            CI.CART_ID,
                            CI.INVENTORY_ID,
                            CI.QUANTITY,
                            CI.UNIT_PRICE_CENTS,
                            CI.CURRENCY_CODE,
                            I.SERIES_CODE,
                            I.STYLE_CODE,
                            I.SERIAL_NUMBER,
                            I.MODIFIER_CODE,
                            I.SELLER_ID,
                            PV.SERIES_CODE || PV.STYLE_CODE || PV.SERIAL_NUMBER ||
                            PV.MODIFIER_CODE AS SKU,
                            S.DESCRIPTION AS SERIES_NAME,
                            ST.DESCRIPTION AS STYLE_NAME,
                            PT.DESCRIPTION AS PRODUCT_NAME,
                            SM.DESCRIPTION AS MODIFIER_NAME,
                            VI.URL
                        FROM USER01.CARTS C
                        INNER JOIN USER01.CART_ITEMS CI
                            ON C.ID = CI.CART_ID
                        INNER JOIN USER01.INVENTORY I
                            ON CI.INVENTORY_ID = I.ID
                        INNER JOIN USER01.PRODUCT_VARIANTS PV
                            ON I.SERIES_CODE = PV.SERIES_CODE
                        AND I.STYLE_CODE = PV.STYLE_CODE
                        AND I.SERIAL_NUMBER = PV.SERIAL_NUMBER
                        AND I.MODIFIER_CODE = PV.MODIFIER_CODE
                        INNER JOIN USER01.PRODUCT_TYPES PT
                            ON PV.SERIES_CODE = PT.SERIES_CODE
                        AND PV.STYLE_CODE = PT.STYLE_CODE
                        AND PV.SERIAL_NUMBER = PT.SERIAL_NUMBER
                        INNER JOIN USER01.SERIES S
                            ON PT.SERIES_CODE = S.CODE
                        INNER JOIN USER01.STYLES ST
                            ON PT.STYLE_CODE = ST.CODE
                        INNER JOIN USER01.STYLE_MODIFIERS SM
                            ON PV.STYLE_CODE = SM.STYLE_CODE
                        AND PV.MODIFIER_CODE = SM.MODIFIER_CODE
                        LEFT JOIN USER01.VARIANT_IMAGES VI
                            ON PV.SERIES_CODE = VI.SERIES_CODE
                        AND PV.STYLE_CODE = VI.STYLE_CODE
                        AND PV.SERIAL_NUMBER = VI.SERIAL_NUMBER
                        AND PV.MODIFIER_CODE = VI.MODIFIER_CODE
                        WHERE C.USER_ID = ?
                        AND C.STATUS = 'active';
                    """
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, user_id)
            ibm_db.execute(stmt)
            results = []
            row = ibm_db.fetch_assoc(stmt)
            while row:
                results.append(row)
                row = ibm_db.fetch_assoc(stmt)
            return {"status": "success", "output": results}
        except Exception as e:
            return {"status": "error", "reason": str(e)}
        finally:
            self.pool.return_connection(conn)

    def add_item(self, cart_id, inventory_id, quantity, unit_price_cents, currency_code):
        """
        Add a new item to the shopping cart.
        
        Inputs:
            cart_id (int): Cart's unique identifier
            inventory_id (int): Inventory item to add
            quantity (int): Number of items to add
            unit_price_cents (int): Price per unit in cents
            currency_code (str): Currency code (e.g., 'USD')
        
        Outputs:
            dict: {"status": "success"} on success
                  {"status": "error", "reason": str} on failure
        
        Side Effects:
            Inserts new cart item in CART_ITEMS table
            Commits transaction on success, rolls back on failure
        
        Notes:
            Does not check for duplicate items - use check_existing_cart_item first
        """
        conn = self.pool.get_connection()
        try:
            sql="""
                    INSERT INTO USER01.CART_ITEMS
                        (CART_ID, INVENTORY_ID, QUANTITY, UNIT_PRICE_CENTS,
                        CURRENCY_CODE)
                    VALUES (?, ?, ?, ?, ?)
                    """
            stmt=ibm_db.prepare(conn,sql)
            ibm_db.bind_param(stmt,1,cart_id )
            ibm_db.bind_param(stmt,2,inventory_id) 
            ibm_db.bind_param(stmt,3,quantity)
            ibm_db.bind_param(stmt,4,unit_price_cents)
            ibm_db.bind_param(stmt,5,currency_code)
            ibm_db.execute(stmt)
            ibm_db.commit(conn)
            return {"status": "success"}
        except Exception as e:
            ibm_db.rollback(conn)
            return {"status": "error", "reason": str(e)}
        finally:
            self.pool.return_connection(conn)

    def remove_item(self, cart_id, cart_item_id):
        """
        Remove a specific item from the shopping cart.
        
        Inputs:
            cart_id (int): Cart's unique identifier
            cart_item_id (int): Cart item ID to remove
        
        Outputs:
            dict: {"status": "success"} if item removed
                  {"status": "error", "reason": "Cart item not found"} if item doesn't exist
                  {"status": "error", "reason": str} on other failure
        
        Side Effects:
            Deletes cart item record from CART_ITEMS table
            Commits transaction on success, rolls back on failure
        
        Notes:
            Verifies both cart_id and cart_item_id match for security
        """
        conn = self.pool.get_connection()
        try:
            sql = """
                    DELETE FROM USER01.CART_ITEMS
                    WHERE CART_ID = ?
                    AND ID = ?
                 """
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, cart_id)
            ibm_db.bind_param(stmt, 2, cart_item_id)
            ibm_db.execute(stmt)
            
            num_rows = ibm_db.num_rows(stmt)
            if num_rows == 0:
                return {"status": "error", "reason": "Cart item not found"}
            
            ibm_db.commit(conn)
            return {"status": "success"}
        except Exception as e:
            ibm_db.rollback(conn)
            return {"status": "error", "reason": str(e)}
        finally:
            self.pool.return_connection(conn)

    def remove_entire_cart(self, user_id):
        """
        Remove all items from user's cart (used after checkout).
        
        Inputs:
            user_id (int): User's unique identifier
        
        Outputs:
            dict: {"status": "success", "rows_deleted": int} on success
                  {"status": "error", "reason": "Cart is already empty or doesn't exist"} if no items
                  {"status": "error", "reason": str} on other failure
        
        Side Effects:
            Deletes all cart items for the user's active cart
            Commits transaction on success, rolls back on failure
        
        Notes:
            Uses subquery to find cart ID by user ID
            Cart record remains (only items are deleted)
        """
        conn = self.pool.get_connection()
        try:
            sql = """
                DELETE FROM USER01.CART_ITEMS
                WHERE CART_ID IN (
                    SELECT ID 
                    FROM USER01.CARTS 
                    WHERE USER_ID = ?
                )"""
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, user_id)
            ibm_db.execute(stmt)
            
            num_rows = ibm_db.num_rows(stmt)
            if num_rows == 0:
                return {"status": "error", "reason": "Cart is already empty or doesn't exist"}
            
            ibm_db.commit(conn)
            return {"status": "success", "rows_deleted": num_rows}
        except Exception as e:
            ibm_db.rollback(conn)
            return {"status": "error", "reason": str(e)}
        finally:
            self.pool.return_connection(conn)

    def check_existing_cart_item(self, cart_id, inventory_id):
        """
        Check if an inventory item already exists in the cart.
        
        Inputs:
            cart_id (int): Cart's unique identifier
            inventory_id (int): Inventory item to check for
        
        Outputs:
            dict: {"status": "success", "output": list with ID and QUANTITY}
                  {"status": "error", "reason": str} on failure
        
        Notes:
            Returns empty list if item not in cart
            Used to determine whether to add new item or update quantity
        """
        conn = self.pool.get_connection()
        try:
            sql =  """
                    SELECT ID, QUANTITY FROM USER01.CART_ITEMS 
                    WHERE CART_ID = ? AND INVENTORY_ID = ?
                    """
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, cart_id)
            ibm_db.bind_param(stmt, 2, inventory_id)
            ibm_db.execute(stmt)
            results = []
            row = ibm_db.fetch_assoc(stmt)
            while row:
                results.append(row)
                row = ibm_db.fetch_assoc(stmt)
            return {"status": "success", "output": results}
        except Exception as e:
            return {"status": "error", "reason": str(e)}
        finally:
            self.pool.return_connection(conn)

    def update_quantity(self, cart_items_id, quantity):
        """
        Update the quantity of an existing cart item.
        
        Inputs:
            cart_items_id (int): Cart item's unique identifier
            quantity (int): New quantity value
        
        Outputs:
            dict: {"status": "success"} if quantity updated
                  {"status": "error", "reason": "Order not found"} if item doesn't exist
                  {"status": "error", "reason": str} on other failure
        
        Side Effects:
            Updates QUANTITY field in CART_ITEMS table
            Commits transaction on success, rolls back on failure
        
        Notes:
            Used when user changes quantity of item already in cart
        """
        conn = self.pool.get_connection()
        try:
            sql = """ UPDATE USER01.CART_ITEMS
                    SET QUANTITY = ?
                    WHERE ID = ?  
                    """
            stmt = ibm_db.prepare(conn, sql)
            ibm_db.bind_param(stmt, 1, quantity)
            ibm_db.bind_param(stmt, 2, cart_items_id)
            ibm_db.execute(stmt)
            num_rows = ibm_db.num_rows(stmt)
        
            if num_rows == 0:
                return {"status": "error", "reason": "Cart item not found"}
            
            ibm_db.commit(conn)
            return {"status": "success"}
        except Exception as e:
            ibm_db.rollback(conn)
            return {"status": "error", "reason": str(e)}
        finally:
            self.pool.return_connection(conn)